import { chromium } from "playwright";
const out = "C:/Users/User/AppData/Local/Temp/claude/c--Users-User-Desktop-rehan-portfolio/b3177b9f-09af-400a-876c-b2ddfc1b6b7c/scratchpad";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, colorScheme: "dark" });
const errors = [];
page.on("console", (msg) => { if (msg.type() === "error") errors.push(msg.text()); });
await page.goto("http://localhost:5188", { waitUntil: "networkidle" });
await page.evaluate(() => document.querySelector("iframe")?.scrollIntoView({ block: "center" }));
await page.waitForTimeout(2000);
await page.screenshot({ path: `${out}/reel-in-page.png` });
console.log("CONSOLE_ERRORS:", JSON.stringify(errors));
await browser.close();
